import {
    GestionTallerProdClients,
    GestionTallerProdSuppliers,
    GestionTallerProdVehicles,
    GestionTallerProdVehicleReceipts,
    GestionTallerProdClientHistory,
    GestionTallerProdQuotes,
    GestionTallerProdQuoteItems,
    GestionTallerProdAccountsReceivable,
    GestionTallerProdAccountsPayable,
    GestionTallerProdFinancialTransactions,
    GestionTallerProdPartsCatalog,
    GestionTallerProdPendingPurchases,
    GestionTallerProdEmployees,
    GestionTallerProdDeliveryNotes,
    GestionTallerProdDeliveryNoteItems,
    GestionTallerProdInspectionCards,
    GestionTallerProdBodyShopMaterials,
    GestionTallerProdBodyShopOrders,
    GestionTallerProdMonthlyControl,
    GestionTallerProdWorkContracts,
    GestionTallerProdCommunications,
    GestionTallerProdInspectionVideo,
    GestionTallerProdInspectionAnalysis,
    GestionTallerProdCatalogState,
    GestionTallerProdStats,
    GeminiGarageCopilot
} from './entities';

export const ENTITY_REGISTRY: Record<string, any> = {
    'GestionTallerProd_clients': GestionTallerProdClients,
    'GestionTallerProd_suppliers': GestionTallerProdSuppliers,
    'GestionTallerProd_vehicles': GestionTallerProdVehicles,
    'GestionTallerProd_vehicle_receipts': GestionTallerProdVehicleReceipts,
    'vehicle_receipts': GestionTallerProdVehicleReceipts,
    'receipts': GestionTallerProdVehicleReceipts,
    'GestionTallerProd_client_history': GestionTallerProdClientHistory,
    'GestionTallerProd_quotes': GestionTallerProdQuotes,
    'GestionTallerProd_quote_items': GestionTallerProdQuoteItems,
    'GestionTallerProd_accounts_receivable': GestionTallerProdAccountsReceivable,
    'GestionTallerProd_accounts_payable': GestionTallerProdAccountsPayable,
    'GestionTallerProd_financial_transactions': GestionTallerProdFinancialTransactions,
    'GestionTallerProd_parts_catalog': GestionTallerProdPartsCatalog,
    'GestionTallerProd_pending_purchases': GestionTallerProdPendingPurchases,
    'GestionTallerProd_employees': GestionTallerProdEmployees,
    'GestionTallerProd_delivery_notes': GestionTallerProdDeliveryNotes,
    'GestionTallerProd_delivery_note_items': GestionTallerProdDeliveryNoteItems,
    'GestionTallerProd_inspection_cards': GestionTallerProdInspectionCards,
    'GestionTallerProd_body_shop_materials': GestionTallerProdBodyShopMaterials,
    'GestionTallerProd_body_shop_orders': GestionTallerProdBodyShopOrders,
    'GestionTallerProd_monthly_control': GestionTallerProdMonthlyControl,
    'GestionTallerProd_work_contracts': GestionTallerProdWorkContracts,
    'GestionTallerProd_communications': GestionTallerProdCommunications,
    'GestionTallerProd_inspection_video': GestionTallerProdInspectionVideo,
    'GestionTallerProd_inspection_analysis': GestionTallerProdInspectionAnalysis,
    'GestionTallerProd_catalog_state': GestionTallerProdCatalogState,
    'GestionTallerProd_catalogState': GestionTallerProdCatalogState,
    'catalog_state': GestionTallerProdCatalogState,
    'catalogState': GestionTallerProdCatalogState,
    'vehicle_status': GestionTallerProdCatalogState,
    'vehicle_brands_models': GestionTallerProdCatalogState,
    'vehicle_types': GestionTallerProdCatalogState,
    'GestionTallerProd_stats': GestionTallerProdStats,
    'stats': GestionTallerProdStats,

    // Gemini AI Copilot de Taller
    'gemini_copilot': GeminiGarageCopilot,
    'GestionTallerProd_gemini_copilot': GeminiGarageCopilot,
    'copilot': GeminiGarageCopilot,
    'geminiCopilot': GeminiGarageCopilot,
    'GeminiGarageCopilot': GeminiGarageCopilot
};
